psql -U admin hello

DROP DATABASE hello;

CREATE TABLE IF NOT EXISTS welcome(
    id SERIAL NOT NULL PRIMARY KEY,
    msg VARCHAR(50) NOT NULL
);

DROP TABLE welcome;

INSERT INTO welcome VALUES(1,'WELCOME TO MY APP, ONLINE IN HEROKU SAAS!');
INSERT INTO welcome VALUES(2,'BIEN VENIDOS A MI APP, ONLINE EN LO SAAS HEROKU!');
INSERT INTO welcome VALUES(3,'BEM VINDO A MEU APP, ONLINE NO SAAS HEROKU!');
/*deploy*/
    